
###
GET  http://localhost:3000/api/users/enter
Content-Type: application/json

###
POST  http://localhost:3000/api/users/enter
Content-Type: application/json

{
	"phone": 1
}

###
POST  http://localhost:3000/api/users/enter
Content-Type: application/json

{
	"email": "client11@client.com"
}

###
POST  http://localhost:3000/api/client-test
Content-Type: application/json

{
	"name": "kkh5", "email": "kkh5@kkh.com"
}