### Global Scope

### @index=51
# @title = /api/users/:id/reviewNew
@cookie51=carrotsession=Fe26.2*1*c4eee98cea7bcba97a9e97e416f2dc19617680e4dd58a958acd2672fcb8a579a*fTWUG6VLGlKEASouXeDdnA*QJMcisZIc5wH8DAQABnKH3IMb0KNCdOs9nzYHwAmIJQ*1727581743707*a088c080605287ae07125befd1b28adb06c350df9d258ff203d64afa47391799*BDhZoKQhXNytBXepFeQOhaQ04jCKNNOYSDbSAVvED0c~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
@productId51=1
@createdForId51=1
GET http://localhost:3000/api/products/{{productId51}}/checkReviewWritable
Cookie: {{cookie51}}
Content-Type: application/json

{
  "createdForId": "{{createdForId51}}",
  "reviewType": "BuyerReview"
}

### @index=50
# @title = /api/users/:id/reviewNew
@cookie50=carrotsession=Fe26.2*1*dffc78197b39868ca1db5581befa324443b460c3ae6e08d67c69d6879ce5d1de*dkIe0tylw_-UwJKULZdasA*2hJUtgeNt-iiPeZCgHCp-oRg8hdQZEpbSfZBSs4g59w*1726977090272*ee1329e4303700ea6b47263f8c583b9d5b53d1bff5cf56e56c48a83b175886e6*TOuNfIfkxl7jHl0TVLQ84Yes_NUL9BS_ze114dtG7gs~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
@userId50=3
GET http://localhost:3000/api/users/{{userId50}}/simpleProfile
Cookie: {{cookie50}}
Content-Type: application/json

### @index=49
# @title = /api/product/[id]/reviewNew
@cookie49=carrotsession=Fe26.2*1*dffc78197b39868ca1db5581befa324443b460c3ae6e08d67c69d6879ce5d1de*dkIe0tylw_-UwJKULZdasA*2hJUtgeNt-iiPeZCgHCp-oRg8hdQZEpbSfZBSs4g59w*1726977090272*ee1329e4303700ea6b47263f8c583b9d5b53d1bff5cf56e56c48a83b175886e6*TOuNfIfkxl7jHl0TVLQ84Yes_NUL9BS_ze114dtG7gs~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
@review49=일본 '사커 다이제스트'는 6일 축구 이적 전문 사이트 '트랜스퍼마르크트' 자료를 인용, 33년 만에 나폴리의 세리에 A 우승에 기여한 한국 대표팀 수비수 김민재의 평가가 치솟고 있다고 전하며 아시아축구연맹(AFC) 소속 국가 선수 몸값 톱 10을 정리해 관심을 모았다.
@score49=4
@createdForId49=6
@productId49=7
POST http://localhost:3000/api/products/{{productId49}}/reviewNew
Cookie: {{cookie49}}
Content-Type: application/json

{
  "review": "{{review49}}",
  "score": "{{score49}}",
  "createdForId": "{{createdForId49}}",
  "reviewType": "SellerReview"
}

### @index=48
# @title = /api/users/:id/reviewNew
@cookie48=carrotsession=Fe26.2*1*caec73846f82fc1000acf69874d861250dac5633cf320ac6c1f132840975f51f*yo_K-sNho6FGnPMPwe-9Hg*yM_2g2QNCOIcA0RBPLdz6Eddxd4vrdtKwoYNe5rXh-A*1726386303597*c60e716d686249cefeef4823cafbcf484c9c22255fb0b5c2902ce31e5bac53a7*hZ-SHj1AuYe2nH8bb6WjHHYiq1PXhMPlI2KssobRmhA~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
# @prompt userId48 Your userID
GET http://localhost:3000/api/users/{{userId48}}/reviewNew
Cookie: {{cookie48}}
Content-Type: application/json

{"filterType": "createdBy"}

### @index=47
# @title = /api/products/:id
@cookie47=carrotsession=Fe26.2*1*aa94a242d07ed5e50d05223e590c470dea0aabc98be64b9240b41fd32c93ea05*1eI0rQodaQgCDZphaJLGjQ*miv0ne_9iTi8x_hnso0WujaYus_u8-B8Dqv_wwyE-D4*1719119550711*a575562d6c2a33703ebcc4cdd86e0af344f08d485669198c4036029bf6b12287*zE7DD5sfEHslgXIly_kJQL3N09JEOHl1dRZpiAaXjqI~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
# @prompt idForSale47 Your productID for sale
POST  http://localhost:3000/api/products/{{idForSale47}}
Cookie: {{cookie47}}
Content-Type: application/json

{"buyerId": "6"}

### @index=46
# @title = /api/products/:id
@cookie46=carrotsession=Fe26.2*1*9f4cfa13aa24a341dbcc6c61d9a036009b04ace5b4c831e54ec3894db6545443*hjr5EcHKfR8tLPiVkUwNsw*VM6G9XvGBGHnLhB1ZgTEYE4DF_b2wZYUzy78l-xG9kA*1717912993265*70a01b52d53768f49184fa1b3d1affde5d18033d6b1086568d8dca301f82c06e*FY1b_6ZUcM4ElwibuLYr5Dry2MYyGob5IIslbvj8t24~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
# @prompt idForSale46 Your productID for sale
GET http://localhost:3000/api/products/{{idForSale46}}
Cookie: {{cookie46}}
Content-Type: application/json

### @index=45
# @title = /api/products/:id/reservation
@cookie45=carrotsession=Fe26.2*1*8451570640afd1f5557b4b338fff2bc8e8254cc6826aedfbbce750866406c9cc*Yi4bMgjgE9BmTx9TxwptNg*3XpFlBeaZN9PpOqsZc_dKB5a94AQ9ZbVUQe8-nf_Lhw*1719115629742*945381c932b3ef3917b1aa2689cb5fe7c5c7c21dc9c7cde3027265dce70543df*QbgKlviNiT8wGqy8fri3xWTl8-QbPl1COmBpzpHwB3Q~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
# @prompt idForProduct45 Your productID
GET  http://localhost:3000/api/products/{{idForProduct45}}/reservation
Cookie: {{cookie45}}
Content-Type: application/json

### @index=45
# @title = /api/products/:id/reservation
@cookie45=carrotsession=Fe26.2*1*aa94a242d07ed5e50d05223e590c470dea0aabc98be64b9240b41fd32c93ea05*1eI0rQodaQgCDZphaJLGjQ*miv0ne_9iTi8x_hnso0WujaYus_u8-B8Dqv_wwyE-D4*1719119550711*a575562d6c2a33703ebcc4cdd86e0af344f08d485669198c4036029bf6b12287*zE7DD5sfEHslgXIly_kJQL3N09JEOHl1dRZpiAaXjqI~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
# @prompt idForProduct45 Your productID
POST  http://localhost:3000/api/products/{{idForProduct45}}/reservation
Cookie: {{cookie45}}
Content-Type: application/json

{"buyerId" : "6"}

### @index=44
# @title = https://api.cloudflare.com/client/v4/accounts/<ACCOUNT_ID>/stream/
GET  https://api.cloudflare.com/client/v4/accounts/{{$dotenv CF_ID}}/stream/
Authorization: Bearer {{$dotenv CF_STREAM_TOKEN}}
Content-Type: application/json

### @index=44
# @title = https://api.cloudflare.com/client/v4/accounts/<ACCOUNT_ID>/stream/live_inputs/<LIVE_INPUT_UID>/videos
# @prompt LIVE_INPUT_UID44 Your LIVE_INPUT_UID
GET  https://api.cloudflare.com/client/v4/accounts/{{$dotenv CF_ID}}/stream/live_inputs/{{LIVE_INPUT_UID44}}/videos
Authorization: Bearer {{$dotenv CF_STREAM_TOKEN}}
Content-Type: application/json

### @index=43
# @title = https://api.cloudflare.com/client/v4/accounts/<ACCOUNT_ID>/stream/live_inputs
POST  https://api.cloudflare.com/client/v4/accounts/{{$dotenv CF_ID}}/stream/live_inputs
Authorization: Bearer {{$dotenv CF_STREAM_TOKEN}}
Content-Type: application/json

{"meta": {"name":"test stream"},"recording": { "mode": "automatic" }}

### @index=42
# @title = /api/images/:filename
@cookie42=carrotsession=Fe26.2*1*5d4af2ff2ae9ef96fb10be7940241f7561eb58e553fa9f0bae5e27fc75be6cab*AqbiNShZXq_ZCWven1qOhw*GOGK8cATDxlPNzW2H4N526-CbCF4C2v1Ls9gb-c7IY4*1685939200585*41c1ed75611c910cda706cbc59129a54d0c52135ec7135008671b4966e7bd139*9MMAO8zEtF3JbanKwi5KjOeWAOZIXILGimYN6oxF4fs~2
# @prompt filename42 Your filename for image
GET  http://localhost:3000/api/images/{{filename42}}
Cookie: {{cookie41}}
Content-Type: application/json

### @index=41
# @title = /api/products/:id/sale
@cookie41=carrotsession=Fe26.2*1*bf3bcb8285ff6ce42986f5bd7d30a16a880440da21c9e49d63d7e72f0f2be95e*bohVeI7JMHS6okSSZa-8qg*HDH_5MK6h1HfY2MaK-o3Jf5J0tWUXMGI9Pn8yB4xHbM*1685074656377*0d3b86fe3f6d6c7f4f32d30ce3d24cbe85fb78b843836b58cb40746dcd531500*SiM-A5a6OOmTukGmU4yxXxGFe12_LBYN0eETkv9Xyps~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
# @prompt idForSale41 Your productID for sale
POST  http://localhost:3000/api/products/{{idForSale41}}/sale
Cookie: {{cookie41}}
Content-Type: application/json

### @index=40
# @title = /api/users/me/sale
@cookie40=carrotsession=Fe26.2*1*bf3bcb8285ff6ce42986f5bd7d30a16a880440da21c9e49d63d7e72f0f2be95e*bohVeI7JMHS6okSSZa-8qg*HDH_5MK6h1HfY2MaK-o3Jf5J0tWUXMGI9Pn8yB4xHbM*1685074656377*0d3b86fe3f6d6c7f4f32d30ce3d24cbe85fb78b843836b58cb40746dcd531500*SiM-A5a6OOmTukGmU4yxXxGFe12_LBYN0eETkv9Xyps~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
GET  http://localhost:3000/api/users/me/sales
Cookie: {{cookie40}}
Content-Type: application/json

### 
POST http://localhost:3000/api/books/revalidate-books?secret=nalnari
Content-Type: application/json

{
  "id": "18"
}

### 
POST http://localhost:3000/api/books?secret=nalnari
Content-Type: application/json

{
  "id": 8
}


### @index=39
# @title = GET /api/review
@cookie39=carrotsession=Fe26.2*1*dc31d8a0145d6728220eb7fc007ff37f058041b95a330d27703aa9edd9849554*lSF5BXxT7s0b7GfrVXXB4Q*4ZnNaboJ99s5caPo-ygwcV0Sx4HtjVtOG9SEab8NC_8*1684673499102*d0f565d414f4a035efbf13e5f1aa8281bab0492a453af7bd12e0993cd46da4c8*vgRR5em4aGFKHpIqRwecZNC_qsZdwF71iicsVij1VN0~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
GET http://localhost:3000/api/reviews
Cookie: {{cookie39}}

### @index=38
# @title = /api/review
@cookie38=carrotsession=Fe26.2*1*dc31d8a0145d6728220eb7fc007ff37f058041b95a330d27703aa9edd9849554*lSF5BXxT7s0b7GfrVXXB4Q*4ZnNaboJ99s5caPo-ygwcV0Sx4HtjVtOG9SEab8NC_8*1684673499102*d0f565d414f4a035efbf13e5f1aa8281bab0492a453af7bd12e0993cd46da4c8*vgRR5em4aGFKHpIqRwecZNC_qsZdwF71iicsVij1VN0~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
@review38=일본 '사커 다이제스트'는 6일 축구 이적 전문 사이트 '트랜스퍼마르크트' 자료를 인용, 33년 만에 나폴리의 세리에 A 우승에 기여한 한국 대표팀 수비수 김민재의 평가가 치솟고 있다고 전하며 아시아축구연맹(AFC) 소속 국가 선수 몸값 톱 10을 정리해 관심을 모았다.
@score38=4
@createdById38=24
@createdForId38=14
POST http://localhost:3000/api/reviews
Cookie: {{cookie38}}
Content-Type: application/json

{
  "review": "{{review38}}",
  "score": "{{score38}}",
  "createdById": "{{createdById38}}",
  "createdForId": "{{createdForId38}}"
}

###
POST http://localhost:3000/api/revalidate-books
Content-Type: application/json

{
  "id": "9"
}

###
POST http://localhost:3000/api/books
Content-Type: application/json

{
  "id": "17",
  "title": "전국노래자랑",
  "description": "재미있는 영화다!"
}

###
GET http://localhost:4000/books

###
GET http://localhost:4000/books/1

### @index=37
# @title = /api/products
@cookie37=carrotsession=Fe26.2*1*1c9f18835629c4d6248147e173de7ed1969fadf610f68a79882c2e4a8b2f9697*ybNtufkb-G1MVki0_TjEMQ*bOAfkOlUseCrIg1NnHgwBIHfXitgezyjY_HssbdOFko*1684160831149*cb2837f6f5c8fdbdc352f7f60b265c1f52189a94682449de5f2228c752f1ab10*_CzL4ogXokoP-WGQvPDorIpx2oy88OJFI4X4fGuCPs0~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
GET http://localhost:3000/api/products
Cookie: {{cookie37}}
Content-Type: application/json

### @index=36
# @title = /api/users/me
@cookie36=carrotsession=Fe26.2*1*fd67d514e337219c0fd05709b9ec7550ba9a2fa0a5b61a115a5836fbc719337d*allklBU6_S1cKGHT_Q9EHg*7nTibTpsDvPqBE-fjOBs-ZQck6HHFGKg8VX3rpDlMm4*1683530646606*8e1c77d63f5b9c8b82bc2a7026c97b67ef3f5dddef79a2f5cea23a2e66e0e901*qoHsUZ4hb8LS7xgcmcX9mcFCFEcI1t2c_PzzSibXagU~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
GET  http://localhost:3000/api/users/me
Cookie: {{cookie36}}
Content-Type: application/json

### @index=35
# @title = /api/users/me
@cookie35=carrotsession=Fe26.2*1*fd67d514e337219c0fd05709b9ec7550ba9a2fa0a5b61a115a5836fbc719337d*allklBU6_S1cKGHT_Q9EHg*7nTibTpsDvPqBE-fjOBs-ZQck6HHFGKg8VX3rpDlMm4*1683530646606*8e1c77d63f5b9c8b82bc2a7026c97b67ef3f5dddef79a2f5cea23a2e66e0e901*qoHsUZ4hb8LS7xgcmcX9mcFCFEcI1t2c_PzzSibXagU~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
# @prompt name35 Your name
# @prompt email35 Your email
# @prompt phone35 Your phone
POST  http://localhost:3000/api/users/me
Cookie: {{cookie35}}
Content-Type: application/json

{
  "name": "{{name35}}",
  "email": "{{email35}}",
  "phone": {{phone35}}
}

### @index=34
# @title = /api/products/:id/fav
@cookie34=
# @prompt idForFav34 Your productID for fav
POST http://localhost:3000/api/products/{{idForFav34}}/fav
Cookie: {{cookie34}}
Content-Type: application/json

### @index=33
# @title = /api/products
@cookie33=carrotsession=Fe26.2*1*bf3bcb8285ff6ce42986f5bd7d30a16a880440da21c9e49d63d7e72f0f2be95e*bohVeI7JMHS6okSSZa-8qg*HDH_5MK6h1HfY2MaK-o3Jf5J0tWUXMGI9Pn8yB4xHbM*1685074656377*0d3b86fe3f6d6c7f4f32d30ce3d24cbe85fb78b843836b58cb40746dcd531500*SiM-A5a6OOmTukGmU4yxXxGFe12_LBYN0eETkv9Xyps~2; Max-Age=1295940; Path=/; HttpOnly; Secure; SameSite=Lax
@name33=아이폰
@price33=15
@description33=상태좋음
POST http://localhost:3000/api/products
Cookie: {{cookie33}}
Content-Type: application/json

{
  "name": "{{name33}}",
  "price": "{{price33}}",
  "description": "{{description33}}"
}

### @index=32
# @title = /api/products/:id 
@id32=1
@cookie32=
GET http://localhost:3000/api/products/{{id32}}
Cookie: {{cookie32}}
Content-Type: application/json

###
GET www.example.org/sample_page.html HTTP/1.1

### @index=31
# @title = /api/users/confirm 
# @prompt token31 Your token
POST  http://localhost:3000/api/users/confirm
Content-Type: application/json

{
  "token": "{{token31}}"
}

### @index=30
# @title = /api/users/enter 
# @prompt phoneNumber30 Your phone number
POST  http://localhost:3000/api/users/enter
Content-Type: application/json

{
  "phone": "{{phoneNumber30}}"
}

### @index=29
# @title = /api/users/enter
# @prompt email29 Your email
POST  http://localhost:3000/api/users/enter
Content-Type: application/json

{
  "email": "{{email29}}"
}

###
# @title = POST /api/client-test
POST  http://localhost:3000/api/client-test
Content-Type: application/json

###  @index=28
# @title = GET /workspaces/:workspace/channels/all
@workspaceUrl28=cau
GET http://localhost:3095/api/workspaces/{{workspaceUrl28}}/channels/all
Content-Type: application/json

### @index=27
# @title=POST /workspaces/:workspace/dms/:id/images
@workspaceUrl27=slack
@id27=15
@fileName1-27=1.png
@filePath1-27=C:/Users/Song/Pictures/dev/1.png
@imageType1-27=png
@fileName2-27=403-500x500.jpg
@filePath2-27=C:\Users\Song\Pictures\403-500x500.jpg
@imageType2-27=jpeg
POST http://localhost:3095/api/workspaces/{{workspaceUrl27}}/dms/{{id27}}/images
Content-Type: multipart/form-data; boundary=MyWeb

--MyWeb
Content-Disposition: form-data; name="image"; filename="{{fileName1-27}}"
Content-Type: image/{{imageType1-27}}

< {{filePath1-27}}
--MyWeb--

### @index=26
# @title=POST /workspaces/:workspace/dms/:id/chats
@workspaceUrl26=slack
@id26=15
@chat26=test chat 200번째 12 to 15
POST  http://localhost:3095/api/workspaces/{{workspaceUrl26}}/dms/{{id26}}/chats
Content-Type: application/json

{"content": "{{chat26}}"}

### @index=25
# @title=GET /workspaces/:workspace/dms
@workspaceUrl25=slack
GET  http://localhost:3095/api/workspaces/{{workspaceUrl25}}/dms
Content-Type: application/json

### @index=24
# @title=POST /workspaces/:workspace/channels/:channel/images
@workspaceUrl24=slack
@channel24=일반
@fileName1-24=pigFoot.jpg
@filePath1-24=c:/Users/Song/Pictures/pigFoot.jpg
@imageType1-24=jpeg
@fileName2-24=pigFoot.jpg
@filePath2-24=c:/Users/Song/Pictures/pigFoot.jpg
@imageType2-24=jpeg
POST http://localhost:3095/api/workspaces/{{workspaceUrl24}}/channels/{{channel24}}/images
Content-Type: multipart/form-data; boundary=MyWeb

--MyWeb
Content-Disposition: form-data; name="image"; filename="{{fileName1-24}}"
Content-Type: image/{{imageType1-24}}

< {{filePath1-24}}
--MyWeb--

### @index=23
# @title=POST /workspaces/:workspace/channels/:channel/chats
@workspaceUrl23=slack
@channel23=general
@chat23=test chat
POST  http://localhost:3095/api/workspaces/{{workspaceUrl23}}/channels/{{channel23}}/chats
Content-Type: application/json

{"content": "{{chat23}}"}

### @index=22
# @title=GET /workspaces/:workspace/dms/:id/unreads
@workspaceUrl22=slack
@id22=12
@after22=1667620500917
GET  http://localhost:3095/api/workspaces/{{workspaceUrl22}}/dms/{{id22}}/unreads?after={{after22}}
Content-Type: application/json

### @index=21
# @title=GET /workspaces/:workspace/channels/:channel/unreads
@workspaceUrl21=slack
@channel21=일반
@after21=1664845335983
GET  http://localhost:3095/api/workspaces/{{workspaceUrl21}}/channels/{{channel21}}/unreads?after={{after21}}

### @index=20
# @title=GET /workspaces/:workspace/channels/:channel/chats
@workspaceUrl20=slack
@channel20=general
@perPage20=20
@page20=1
GET  http://localhost:3095/api/workspaces/{{workspaceUrl20}}/channels/{{channel20}}/chats?perPage={{perPage20}}&page={{page20}}
Content-Type: application/json

###  @index=19
# @title = DELETE /workspaces/:workspace/members/:id
@workspaceUrl19=dally
@id19=15
DELETE   http://localhost:3095/api/workspaces/{{workspaceUrl19}}/members/{{id19}}
Content-Type: application/json

###  @index=18
# @title = GET /workspaces/:workspace/users/:id
@workspaceUrl18=cau
@id18=13
GET http://localhost:3095/api/workspaces/{{workspaceUrl18}}/users/{{id18}}
Content-Type: application/json

### @index=17
# @title=POST /workspaces/:workspace/channels/:channel/members
@workspaceUrl17=slack
@channel17=Sleact Frontend
@email17=client100@client.com
POST  http://localhost:3095/api/workspaces/{{workspaceUrl17}}/channels/{{channel17}}/members
Content-Type: application/json

{
  "email": "{{email17}}"
}

### @index=16
# @title=POST /workspaces/:workspace/members
@workspaceUrl16=slack
@email16=client200@client.com
POST http://localhost:3095/api/workspaces/{{workspaceUrl16}}/members
Content-Type: application/json

{
  "email": "{{email16}}"
}

###  @index=15
# @title = GET /workspaces/:workspace/channels/:channel
@workspaceUrl15=cau
@channel15=MCL
GET http://localhost:3095/api/workspaces/{{workspaceUrl15}}/channels/{{channel15}}
Content-Type: application/json

### @index=14
# @title=GET /workspaces/:workspace/dms/:id/chats
@workspaceUrl14=slack
@id14=12
@perPage14=20
@page14=1
GET  http://localhost:3095/api/workspaces/{{workspaceUrl14}}/dms/{{id14}}/chats?perPage={{perPage14}}&page={{page14}}
Content-Type: application/json

### @index=13
# @title=POST /users/login
@email13=kimchulsoo@client.com
@password13=121212
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "{{email13}}",
  "password": "{{password13}}" 
}

### @index=12
# @title=GET /workspaces/:workspace/channels/:channel/unreads
@workspaceUrl12=Slack
@channel12=Sleact Frontend
@timestamp12=0
GET  http://localhost:3095/api/workspaces/{{workspaceUrl12}}/channels/{{channel12}}/unread?after={{timestamp12}}
Content-Type: application/json

### @index=11
# @title=GET /workspaces
GET http://localhost:3095/api/workspaces
Content-Type: application/json

### @index=10
# @title=POST /workspaces
@workspaceName10=Prisma로 변환 2
@url10=prisma-migration2
POST http://localhost:3095/api/workspaces
Content-Type: application/json

{ 
  "workspace": "{{workspaceName10}}",  
  "url":  "{{url10}}"        
}

###  @index=9
# @title = GET /workspaces/:workspace/channels
@workspaceUrl9=cau
GET http://localhost:3095/api/workspaces/{{workspaceUrl9}}/channels
Content-Type: application/json

### @index=8
# @title = /workspaces/:workspace/channels/:channel/members
@workspaceUrl8=slack
@channel8=general
@email8=client8@client.com
POST  http://localhost:3095/api/workspaces/{{workspaceUrl8}}/channels/{{channel8}}/members
Content-Type: application/json

{
  "email": "{{email8}}"
}

### @index=7
# @title = GET /workspaces/:workspace/channels/:channel/members
@workspaceUrl7=slack
@channel7=일반
GET  http://localhost:3095/api/workspaces/{{workspaceUrl7}}/channels/{{channel7}}/members
Content-Type: application/json

### @index=6
# @title=GET /workspaces/:workspace/channels/:channel
@workspaceUrl6=slack
@channel6=Sleact Frontend
GET  http://localhost:3095/api/workspaces/{{workspaceUrl6}}/channels/{{channel6}}
Content-Type: application/json

### @index=5
# @title=GET /workspaces/:workspace/dms/:id/chats 
@workspaceUrl5=slack
@id5=12
@perPage5=20
@page5=1
GET  http://localhost:3095/api/workspaces/{{workspaceUrl5}}/dms/{{id5}}/chats?perPage={{perPage5}}&page={{{{perPage5}}}}
Content-Type: application/json

### @index=5
# @title=GET /workspaces/:workspace/channels/:channel/members
@workspaceUrl5=slack
@channel5=Sleact Frontend
GET  http://localhost:3095/api/workspaces/{{workspaceUrl5}}/channels/{{channel5}}/members
Content-Type: application/json

### @index=4
# @title=GET /workspaces/:workspace/members
@workspaceUrl4=slack
GET http://localhost:3095/api/workspaces/{{workspaceUrl4}}/members
Content-Type: application/json

### @index=3
@workspaceUrl3=slack
@channel3=Sleact Frontend
@perPage3=20
@page3=1
GET  http://localhost:3095/api/workspaces/{{workspaceUrl3}}/channels/{{channel3}}/chats?perPage={{perPage3}}&page={{page3}}
Content-Type: application/json

### @index=2
@workspaceUrl2=slack
@channel2 = Sleact Frontend
GET http://localhost:3095/api/workspaces/{{workspaceUrl2}}/channels/{{channel2}}
Content-Type: application/json

### @index=1
# @title=POST /workspaces/:workspace/channels
@workspaceUrl1=cau
@name1=Football
POST http://localhost:3095/api/workspaces/{{workspaceUrl1}}/channels
Content-Type: application/json

{ 
  "name": "{{name1}}"    
}

### 
POST http://localhost:3095/api/users/logout
Content-Type: application/json

### @index=0
# @title=POST /users
@email0=clientNew4@client.com
@nickname0=clientNew4
@password0=121212
POST http://localhost:3095/api/users/
Content-Type: application/json

{
  "email": "{{email0}}",
  "nickname": "{{nickname0}}",
  "password": "{{password0}}"
}

### 
# @title=GET /users
GET http://localhost:3095/api/users/ HTTP/1.1
Content-Type: application/json

### 
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation Login( 
  $username: String!
  $password: String!
){
  login(  
    username: $username,
    password: $password
  ) {
      ok
      token
      error
    }
}

{
  "username": "moon-4",
  "password": "121212"
}

### 
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query SeeProfile($username: String!) {
  seeProfile(username: $username) {
    firstName
    lastName
    username
    email
  }
}

{
  "username": "moon"
}

### 
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation CreateAccount( 
  $firstName: String!
  $lastName: String
  $username: String!
  $email: String!
  $password: String!
){
  createAccount(  
    firstName: $firstName,
    lastName: $lastName,
    username: $username,
    email: $email,
    password: $password
  ) {
      firstName
      lastName
      username
      email
    }
}

{
  "firstName": "Sukdo",
  "lastName": "Moon",
  "username": "moon-4",
  "email": "moon-4@client.com",
  "password": "121212"
}

### 
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Movies {
  movies {
    id 
    title
    year
    genre
  }
}

### 
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Movie($id: Int!) {
  movie(id: $id) {
    id 
    title
    year
    genre
  }
}

{
  "id": 5
}

### 
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation CreateMovie($title: String!, $year: Int!, $genre: String) {
  createMovie(title: $title, year: $year, genre: $genre) {
    id 
    title
    year
    genre    
  }
}

{
    "title": "Star Craft",
    "year": 2022,
    "genre": "Ultra Fantacy"
}

### 
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation DeleteMovie($id: Int!) {
  deleteMovie(id: $id) {
    id 
    title
    year
    genre    
  }
}

{
    "id": 3
}

### 
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation UpdateMovie($id: Int!, $title: String!, $year: Int) {
  updateMovie(id: $id, title: $title, year: $year) {
    id 
    title
    year
    genre    
  }
}

{
    "id": 5,
    "title": "Star Wars",
    "year": 1999
}

### 
# 토큰의 소유자가 user id 15인 경우 code는 user id 13의 것인데도 동작한다.
# 나중에 문제가 없는 것인지 체크가 필요하다.
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTIzNTE5ODV9.L6BYDzFWUNymMmR-kHxuWk_Uqgq3daSjBDgsb0W1Uy0

mutation {
  verifyEmail(input: {
    code: "25fe0319-120a-4ddf-aec3-4deabc061b23"
  }) {
    ok
    error
  }
}

### 
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(input: {
    email: "0604commit@las.com"
    password: "12345"
  }) {
    ok
    error
    token
  }
}

###
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  createAccount(input: {
    email: "0705commit@las.com"
    password: "12345"
    role: Client
  }) {
    ok
    error
  }
}

### 5.12   1
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjEyMjcyNjU0fQ.Tusjvu5cB7iBJp1VFQXgJsmCBbfOmK7NowH1f6tFq6Q

mutation {
  editProfile(input: {
    email: "강정수@hong.com"
    password: "1234512345"
  }) {
    ok
    error
  }
}

###
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsImlhdCI6MTYxMTMzMjQyNH0.KHZX3ANQqHSlquSt7cPwZJ5kIIRz9okdbC2jnmimGhU

query {
  userProfile(userId: 23) {
    ok
    error
    user {
      id
      email
      password
      createdAt
      updatedAt
    }
  }
}

###
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjEyMjcyNjU0fQ.Tusjvu5cB7iBJp1VFQXgJsmCBbfOmK7NowH1f6tFq6Q

query {
  me {
      id
      email
      password
      createdAt
      updatedAt
      role
  }
}

###
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsImlhdCI6MTYxMTMzMjQyNH0.KHZX3ANQqHSlquSt7cPwZJ5kIIRz9okdbC2jnmimGhU

query {
  me {
    email
  }
}

### 5.2 JWT and Modules
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(input: {
    email: "잭시오01@las.com"
    password: "12345"
  }) {
    ok
    error
    token
  }
}

###
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  createAccount(input: {
    email: "0601코밋@las.com"
    password: "12345"
    role: Client
  }) {
    ok
    error
  }
}

### 4.9 Log In part Two
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(input: {
    email: "남진@hong.com"
    password: "12345"
  }) {
    ok
    error
    token
  }
}

### 4.8 Log In part One
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(input: {
    email: "강정수@hong.com"
    password: "1234512345"
  }) {
    ok
    error
    token
  }
}

### 4.5 Create Account Mutation part Three
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  createAccount(input: {
    email: "강정수@hong.com"
    password: "12345"
    role: Client
  }) {
    ok
    error
  }
}

### 4.2
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  hi
}

### 3.8 Update Restaurant part Two
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  updateRestaurant(
    input: {
      id: 9
      data: {
        name: "Updated"
        isVegan: false
      }
    }
  )
}

### 3.7 Update Restaurant part One
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  updateRestaurant(
    input: {
      id: 9
      data: {
        name: "Without isVegan test2"
      }
    }
  )
}

### 3.6 Create Restaurant
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  createRestaurant(
    input: {
      name: "Without isVegan"
    }
  )
}

### 3.4 Create Restaurant
POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  createRestaurant(
    input: {
      name: "kko is a"
      isVegan: false
      address: "123qqqqqq"
      ownersName: "123qqqqqqq"
      categoryName: "123123"
    }
  )
}